git:
  depth: false
language: python
python:
  - "3.7"
before_install:
  - pip install pip --upgrade
install:
  - pip install -r requirements.txt
script:
  - rm -rf .coverage
  - coverage erase
  - pytest tests --cov=ensmallen_experiments --cov-report xml:coverage.xml
  - coverage combine --append || true
  - coverage report
  - coverage xml
  - pylint --errors-only --exit-zero ensmallen_experiments
after_success:
  - coveralls